In [3]:
# Multiple Linear Regression

#Importing pandas library to read CSV data file
import pandas as pd

#Importing numpy to perfom math on arrays
import numpy as np


In [4]:
#Reading CSV data file in Python
dataset = pd.read_csv('Companies.csv')

In [5]:
dataset.head()

City         IT  Staff_Training  Advertising     Profit
0  Paris  165349.20       236897.80    472784.20  182262.83
1   Rome  262597.70       182377.59    443898.53  172792.06
2   Rome  153442.52       172245.55    407934.54  162050.39
3  Paris  244372.42       138672.85    383299.62  282902.99
4   Rome  132207.34        92392.77    366268.42  266287.94

In [6]:
#Extract matrix of features and target from the dataset 
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [7]:
X,y

(array([['Paris', 165349.2, 236897.8, 472784.2],
        ['Rome', 262597.7, 182377.59, 443898.53],
        ['Rome', 153442.52, 172245.55, 407934.54],
        ['Paris', 244372.42, 138672.85, 383299.62],
        ['Rome', 132207.34, 92392.77, 366268.42],
        ['Paris', 232876.9, 99824.72, 362862.36],
        ['Rome', 214625.46, 247298.87, 227726.82],
        ['Paris', 220298.23, 155530.06, 323876.68],
        ['Paris', 220542.52, 138728.95, 322623.29],
        ['Rome', 113334.88, 148679.27, 304982.62],
        ['Rome', 182923.08, 220594.22, 229260.95],
        ['Rome', 200672.96, 92790.62, 249744.55],
        ['Rome', 93863.75, 227320.38, 249839.44],
        ['Rome', 92992.39, 235495.07, 252664.93],
        ['Paris', 119943.24, 256547.42, 256522.92],
        ['Paris', 164523.62, 222626.84, 262776.23],
        ['Rome', 78023.22, 222597.55, 264346.06],
        ['Paris', 94657.26, 245077.58, 282574.32],
        ['Paris', 92749.26, 224275.79, 294929.57],
        ['Rome', 76253.86, 223867.3

In [8]:
# Hotencode categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)

In [9]:
X

array([[0.0, 0.0, 1.0, 0.0, 165349.2, 236897.8, 472784.2],
       [0.0, 0.0, 0.0, 1.0, 262597.7, 182377.59, 443898.53],
       [0.0, 0.0, 0.0, 1.0, 153442.52, 172245.55, 407934.54],
       [0.0, 0.0, 1.0, 0.0, 244372.42, 138672.85, 383299.62],
       [0.0, 0.0, 0.0, 1.0, 132207.34, 92392.77, 366268.42],
       [0.0, 0.0, 1.0, 0.0, 232876.9, 99824.72, 362862.36],
       [0.0, 0.0, 0.0, 1.0, 214625.46, 247298.87, 227726.82],
       [0.0, 0.0, 1.0, 0.0, 220298.23, 155530.06, 323876.68],
       [0.0, 0.0, 1.0, 0.0, 220542.52, 138728.95, 322623.29],
       [0.0, 0.0, 0.0, 1.0, 113334.88, 148679.27, 304982.62],
       [0.0, 0.0, 0.0, 1.0, 182923.08, 220594.22, 229260.95],
       [0.0, 0.0, 0.0, 1.0, 200672.96, 92790.62, 249744.55],
       [0.0, 0.0, 0.0, 1.0, 93863.75, 227320.38, 249839.44],
       [0.0, 0.0, 0.0, 1.0, 92992.39, 235495.07, 252664.93],
       [0.0, 0.0, 1.0, 0.0, 119943.24, 256547.42, 256522.92],
       [0.0, 0.0, 1.0, 0.0, 164523.62, 222626.84, 262776.23],
       [0.0, 0.0, 

In [10]:
#Avoid the dummy variable trap
X = X[:, 1:]

In [11]:
X

array([[0.0, 1.0, 0.0, 165349.2, 236897.8, 472784.2],
       [0.0, 0.0, 1.0, 262597.7, 182377.59, 443898.53],
       [0.0, 0.0, 1.0, 153442.52, 172245.55, 407934.54],
       [0.0, 1.0, 0.0, 244372.42, 138672.85, 383299.62],
       [0.0, 0.0, 1.0, 132207.34, 92392.77, 366268.42],
       [0.0, 1.0, 0.0, 232876.9, 99824.72, 362862.36],
       [0.0, 0.0, 1.0, 214625.46, 247298.87, 227726.82],
       [0.0, 1.0, 0.0, 220298.23, 155530.06, 323876.68],
       [0.0, 1.0, 0.0, 220542.52, 138728.95, 322623.29],
       [0.0, 0.0, 1.0, 113334.88, 148679.27, 304982.62],
       [0.0, 0.0, 1.0, 182923.08, 220594.22, 229260.95],
       [0.0, 0.0, 1.0, 200672.96, 92790.62, 249744.55],
       [0.0, 0.0, 1.0, 93863.75, 227320.38, 249839.44],
       [0.0, 0.0, 1.0, 92992.39, 235495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 256547.42, 256522.92],
       [0.0, 1.0, 0.0, 164523.62, 222626.84, 262776.23],
       [0.0, 0.0, 1.0, 78023.22, 222597.55, 264346.06],
       [0.0, 1.0, 0.0, 94657.26, 245077.58

In [12]:
# Splitting dataset into Training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [13]:
X_test

array([[0.0, 1.0, 0.0, 72207.6, 227864.55, 353283.82],
       [0.0, 1.0, 0.0, 66052.52, 282645.56, 228248.2],
       [0.0, 0.0, 0.0, 153441.51, 101255.55, 407934.54],
       [0.0, 0.0, 1.0, 67532.53, 205752.03, 304768.73],
       [0.0, 1.0, 0.0, 62236.38, 252702.92, 88228.23],
       [1.0, 0.0, 0.0, 131876.9, 99815.71, 361861.36],
       [0.0, 1.0, 0.0, 220298.23, 155530.06, 323876.68],
       [0.0, 0.0, 0.0, 91991.39, 135495.07, 151664.93],
       [0.0, 1.0, 0.0, 46024.02, 85047.44, 205527.64],
       [0.0, 0.0, 0.0, 64664.71, 139553.16, 137961.61],
       [0.0, 0.0, 0.0, 101913.08, 120594.12, 129160.95],
       [0.0, 1.0, 0.0, 65605.48, 253032.06, 117238.38],
       [0.0, 0.0, 1.0, 63408.86, 229229.62, 46085.25],
       [0.0, 1.0, 0.0, 25505.73, 227382.3, 35534.27],
       [0.0, 0.0, 1.0, 46426.07, 257693.92, 120797.67]], dtype=object)

In [14]:
# Build the regression and fit the data
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

reg.fit(X_train,y_train)

LinearRegression()

In [15]:
# Predict the target values
y_pred = reg.predict(X_test)

In [16]:
y_pred

array([161744.57499315, 152122.99084524, 175953.31833415, 149343.50463647,
       139465.28655245, 155808.27674398, 231309.33856501, 128802.45927305,
       133096.30058171, 114303.02581528, 131675.06619122, 143160.93614641,
       130384.7281503 , 116466.32634479, 128065.16841275])

In [17]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[161744.57 205008.32]
 [152122.99 203282.38]
 [175953.32 191050.39]
 [149343.5  208733.99]
 [139465.29  97483.56]
 [155808.28 156991.12]
 [231309.34 255752.6 ]
 [128802.46 134307.35]
 [133096.3   96479.52]
 [114303.03 107404.34]
 [131675.07 156121.95]
 [143160.94 202004.64]
 [130384.73  97427.84]
 [116466.33  69758.98]
 [128065.17  96722.8 ]]


In [18]:
# Check the model accuracy 
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.5445175816109233